const mongoose = require('mongoose');

const monthlyReportSchema = new mongoose.Schema({
    child_id: { type: mongoose.Schema.Types.ObjectId, ref: "Child", required: true },
    teacher_id: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    semester: { type: String, required: true },
    
    // NILAI AGAMA DAN MORAL
    religious_moral: {
        berdoa_sebelum_kegiatan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        berdoa_sebelum_kegiatan_keterangan: { type: String },
        menirukan_sikap_berdoa: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menirukan_sikap_berdoa_keterangan: { type: String },
        menyebutkan_ciptaan_tuhan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebutkan_ciptaan_tuhan_keterangan: { type: String },
        menyayangi_ciptaan_tuhan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyayangi_ciptaan_tuhan_keterangan: { type: String }
    },
    
    // SOSIAL-EMOSI
    social_emotional: {
        menyebut_nama_teman: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_nama_teman_keterangan: { type: String },
        sikap_menolong: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        sikap_menolong_keterangan: { type: String },
        mengucapkan_salam: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengucapkan_salam_keterangan: { type: String },
        mengucapkan_terimakasih: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengucapkan_terimakasih_keterangan: { type: String },
        meminta_dan_memberi_maaf: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        meminta_dan_memberi_maaf_keterangan: { type: String },
        berbagi_mainan_makanan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        berbagi_mainan_makanan_keterangan: { type: String },
        menunggu_giliran: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menunggu_giliran_keterangan: { type: String },
        afeksi_pada_orang_lain: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        afeksi_pada_orang_lain_keterangan: { type: String },
        rasa_percaya_diri: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        rasa_percaya_diri_keterangan: { type: String },
        mengungkapkan_keinginan_bak_bab: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengungkapkan_keinginan_bak_bab_keterangan: { type: String },
        menunjukkan_ekspresi_wajar: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menunjukkan_ekspresi_wajar_keterangan: { type: String },
        meminta_izin_pakai_barang: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        meminta_izin_pakai_barang_keterangan: { type: String },
        berbicara_suara_lembut: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        berbicara_suara_lembut_keterangan: { type: String },
        mengerjakan_tugas_sampai_selesai: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengerjakan_tugas_sampai_selesai_keterangan: { type: String },
        reaksi_terhadap_orang_baru: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        reaksi_terhadap_orang_baru_keterangan: { type: String },
        berinteraksi_dengan_teman: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        berinteraksi_dengan_teman_keterangan: { type: String },
        sikap_kooperatif: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        sikap_kooperatif_keterangan: { type: String },
        memilih_mainan_sendiri: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        memilih_mainan_sendiri_keterangan: { type: String }
    },
    
    // KOGNITIF
    cognitive: {
        menyebut_nama_bagian_tubuh: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_nama_bagian_tubuh_keterangan: { type: String },
        menyebut_nama_benda: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_nama_benda_keterangan: { type: String },
        mengelompokkan_benda: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengelompokkan_benda_keterangan: { type: String },
        mengenal_warna_dasar: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengenal_warna_dasar_keterangan: { type: String },
        menyusun_puzzle: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyusun_puzzle_keterangan: { type: String },
        menceritakan_pengalaman: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menceritakan_pengalaman_keterangan: { type: String },
        membilang_1_5: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        membilang_1_5_keterangan: { type: String },
        mengenal_bentuk_geometri: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengenal_bentuk_geometri_keterangan: { type: String },
        menyebut_ciri_binatang: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_ciri_binatang_keterangan: { type: String },
        mengenal_posisi_objek: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengenal_posisi_objek_keterangan: { type: String },
        mengenal_gejala_alam: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengenal_gejala_alam_keterangan: { type: String },
        mengerjakan_maze: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengerjakan_maze_keterangan: { type: String },
        bermain_peran: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        bermain_peran_keterangan: { type: String },
        menyebut_anggota_tubuh: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_anggota_tubuh_keterangan: { type: String },
        mengenal_rasa_manis_dan_asin: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mengenal_rasa_manis_dan_asin_keterangan: { type: String }
    },
    
    // BAHASA
    language: {
        menyebut_nama_panggilan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_nama_panggilan_keterangan: { type: String },
        menyebut_nama_orangtua: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyebut_nama_orangtua_keterangan: { type: String },
        menyatakan_keinginan: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menyatakan_keinginan_keterangan: { type: String },
        menceritakan_tentang_gambar: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menceritakan_tentang_gambar_keterangan: { type: String },
        memahami_instruksi_sederhana: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        memahami_instruksi_sederhana_keterangan: { type: String },
        menjawab_pertanyaan_ya_tidak: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menjawab_pertanyaan_ya_tidak_keterangan: { type: String },
        menjawab_dengan_kalimat_sederhana: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menjawab_dengan_kalimat_sederhana_keterangan: { type: String },
        mendengarkan_dan_menceritakan_kembali: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        mendengarkan_dan_menceritakan_kembali_keterangan: { type: String },
        menceritakan_pengalaman: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menceritakan_pengalaman_keterangan: { type: String },
        meniru_kata_kata: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        meniru_kata_kata_keterangan: { type: String },
        menggunakan_2_3_kata: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menggunakan_2_3_kata_keterangan: { type: String },
        menggunakan_kata_tanya: { type: String, enum: ["Belum Konsisten", "Konsisten", "Tidak Teramati"], default: "Belum Konsisten" },
        menggunakan_kata_tanya_keterangan: { type: String }
    },
    
    // MOTORIK KASAR
    gross_motor: {
        naik_tangga: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        naik_tangga_keterangan: { type: String },
        turun_tangga: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        turun_tangga_keterangan: { type: String },
        berlari_lurus: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        berlari_lurus_keterangan: { type: String },
        mendorong_menarik_mainan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mendorong_menarik_mainan_keterangan: { type: String },
        melompat_di_tempat: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melompat_di_tempat_keterangan: { type: String },
        melompat_dari_ketinggian: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melompat_dari_ketinggian_keterangan: { type: String },
        berdiri_satu_kaki: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        berdiri_satu_kaki_keterangan: { type: String },
        berjalan_jinjit: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        berjalan_jinjit_keterangan: { type: String },
        menendang_bola: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menendang_bola_keterangan: { type: String },
        melempar_bola: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melempar_bola_keterangan: { type: String },
        menangkap_bola: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menangkap_bola_keterangan: { type: String },
        mengikuti_gerakan_sederhana: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mengikuti_gerakan_sederhana_keterangan: { type: String },
        memanjat: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memanjat_keterangan: { type: String },
        melompat_dua_kaki: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melompat_dua_kaki_keterangan: { type: String },
        menggulirkan_bola: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menggulirkan_bola_keterangan: { type: String },
        berguling_di_matras: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        berguling_di_matras_keterangan: { type: String },
        merangkak_dan_merayap: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        merangkak_dan_merayap_keterangan: { type: String }
    },
    
    // MOTORIK HALUS
    fine_motor: {
        memindahkan_benda: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memindahkan_benda_keterangan: { type: String },
        membuka_tutup_gelas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuka_tutup_gelas_keterangan: { type: String },
        meremas_kertas_dan_spons: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        meremas_kertas_dan_spons_keterangan: { type: String },
        merobek_kertas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        merobek_kertas_keterangan: { type: String },
        menyusun_menara_balok: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menyusun_menara_balok_keterangan: { type: String },
        membuka_retseleting: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuka_retseleting_keterangan: { type: String },
        menutup_retseleting: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menutup_retseleting_keterangan: { type: String },
        mencoret_bebas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mencoret_bebas_keterangan: { type: String },
        membuka_tutup_gunting: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuka_tutup_gunting_keterangan: { type: String },
        membalik_halaman_buku: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membalik_halaman_buku_keterangan: { type: String },
        melipat_kertas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melipat_kertas_keterangan: { type: String },
        koordinasi_jari_tangan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        koordinasi_jari_tangan_keterangan: { type: String },
        menempel_kertas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menempel_kertas_keterangan: { type: String },
        menggunting_tanpa_pola: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menggunting_tanpa_pola_keterangan: { type: String },
        memegang_krayon: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memegang_krayon_keterangan: { type: String },
        menarik_garis: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menarik_garis_keterangan: { type: String },
        memegang_benda_kecil: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memegang_benda_kecil_keterangan: { type: String }
    },
    
    // KEMANDIRIAN
    independence: {
        melepas_sepatu_tak_bertali: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melepas_sepatu_tak_bertali_keterangan: { type: String },
        memakai_sepatu_tak_bertali: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memakai_sepatu_tak_bertali_keterangan: { type: String },
        meletakkan_sandal_tas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        meletakkan_sandal_tas_keterangan: { type: String },
        mengembalikan_mainan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mengembalikan_mainan_keterangan: { type: String },
        memakai_sandal: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memakai_sandal_keterangan: { type: String },
        mengeluarkan_tempat_makan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mengeluarkan_tempat_makan_keterangan: { type: String },
        memasukkan_tempat_makan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memasukkan_tempat_makan_keterangan: { type: String },
        mencuci_tangan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        mencuci_tangan_keterangan: { type: String },
        membuang_sampah: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuang_sampah_keterangan: { type: String },
        menggunakan_sendok: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menggunakan_sendok_keterangan: { type: String },
        menaik_turunkan_celana: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menaik_turunkan_celana_keterangan: { type: String },
        menyuap_makanan_sendiri: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menyuap_makanan_sendiri_keterangan: { type: String },
        minum_dari_gelas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        minum_dari_gelas_keterangan: { type: String },
        duduk_tenang_saat_makan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        duduk_tenang_saat_makan_keterangan: { type: String },
        bak_bab_di_kloset: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        bak_bab_di_kloset_keterangan: { type: String },
        menyikat_gigi_dengan_bantuan: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menyikat_gigi_dengan_bantuan_keterangan: { type: String },
        melepas_baju_tanpa_kancing: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        melepas_baju_tanpa_kancing_keterangan: { type: String },
        memasukkan_tangan_ke_baju: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memasukkan_tangan_ke_baju_keterangan: { type: String },
        memasukkan_kaki_ke_celana: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        memasukkan_kaki_ke_celana_keterangan: { type: String }
    },
    
    // SENI
    art: {
        menari_mengikuti_irama: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        menari_mengikuti_irama_keterangan: { type: String },
        membuat_coretan_dengan_kuas: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuat_coretan_dengan_kuas_keterangan: { type: String },
        membuat_bentuk_plastisin: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        membuat_bentuk_plastisin_keterangan: { type: String },
        bernyanyi_lagu: { type: String, enum: ["Bantuan Fisik", "Bantuan Verbal", "Mandiri", "Tidak Teramati"], default: "Tidak Teramati" },
        bernyanyi_lagu_keterangan: { type: String }
    },
    
}, { timestamps: true });

const MonthlyReport = mongoose.model("MonthlyReport", monthlyReportSchema);
module.exports = MonthlyReport;